# archivo de configuración de DB (sin queries embebidas)
# db.url puede apuntar a la base de datos deseada
db.url=jdbc:mysql://localhost:3306/test_db
db.user=root
db.password=123456789
db.driver=com.mysql.cj.jdbc.Driver
db.poolSize=10
# indicar archivo de queries (relativo a resources o ruta absoluta)
queriesFile=queries.properties
